server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disperts?serverTimezone=GMT%2B8
    username: root
    password: Test@1234
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  secret: DolphinFeedSecretKey